package:
   name: fermi-f2c
   version: "0.0.0"

source:
   git_url: https://github.com/juanjosegarciaripoll/f2c.git

build:
  number: 0

requirements:
   build:
      - autoconf
      - automake
      - libtool
      - m4
